amqp.host:
amqp.port: 5671
amqp.user: user
amqp.password: password

amqp.consumer.driver-command: topic-driver-command
amqp.subscription.driver-command: driver-service
amqp.producer.driver-event: topic-driver-event
amqp.producer.ride-event: topic-ride-event

amqp.query: transport.trustAll=false&transport.verifyHost=true
amqp.protocol: amqps
amqp.pool.explicit-producer-cache-size: 5
amqp.pool.use-anonymous-producers: false

http.port: 8080

# delay before sending a `DriverAssignedEvent` message
driver.assigned.min.delay: 1
driver.assigned.max.delay: 3
# delay before sending a `RideStartedEvent` message
ride.started.min.delay: 5
ride.started.max.delay: 10
# delay before sending a `RideEndedEvent` message
ride.ended.min.delay: 5
ride.ended.max.delay: 10

service-name: driver-service
reporter-log-spans: false
sampler-type: ratelimiting
sampler-param: 1
# const
# sampler-type: const
# sampler-param: 1
agent-host: localhost
agent-port: 6831